sudo: required
services:
    - docker

before_install:
    - docker build -t react -f ./client/Dockerfile.dev ./client

script: docker run -e CI=true react npm run test

after_success:
  - docker build -t roquechan/multi-client ./client
  - docker build -t roquechan/multi-nginx ./nginx
  - docker build -t roquechan/multi-server ./server
  - docker build -t roquechan/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push roquechan/multi-client
  - docker push roquechan/multi-nginx
  - docker push roquechan/multi-server
  - docker push roquechan/multi-worker


deploy:
    provider: elasticbeanstalk
    region: 'eu-west-2'
    app: 'multi-docker'
    env: 'MultiDocker-env`'
    bucket_name: 'elasticbeanstalk-eu-west-2-583370836638'
    bucket_path: 'multi-docker'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY